CREATE DATABASE customer_behavior;
USE customer_behavior;
SELECT * FROM customer;
##Q1. What is the total revenue generated by male vs. female customers?
SELECT Gender , sum(`Purchase Amount (USD)`)
FROM customer
group by Gender;

##Q2. Which customers used a discount but still spent more than the average purchase amount? 

SELECT `Customer ID`, `Purchase Amount (USD)` 
from customer 
where `Discount Applied` = 'Yes' and `Purchase Amount (USD)` >= (select AVG(`Purchase Amount (USD)`) from customer);

##Q3. Which are the top 5 products with the highest average review rating?
SELECT `Item Purchased` , round(AVG(`Review Rating`), 2) AS APR
FROM customer
group by `Item Purchased`
order by avg(`Review Rating`)desc
limit 5;

##Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select  `Shipping Type`,
round(avg(`Purchase Amount (USD)`),2)
from customer
where `Shipping Type` in ('Standard','Express')
group by `Shipping Type`;

##Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT `Subscription Status`,
count(`Customer ID`) AS TOTAL_CUSTOMERS,
round(AVG(`Purchase Amount (USD)`),2) AS AVG_SPEND,
ROUND(sum(`Purchase Amount (USD)`),2) AS TOTAL_REVENUE
FROM customer
group by `Subscription Status`
order by TOTAL_REVENUE, AVG_SPEND DESC;

##Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT `Item Purchased`,
       ROUND(100.0 * SUM(CASE WHEN `Discount Applied` = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY `Item Purchased`
ORDER BY discount_rate DESC
LIMIT 5;

##Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as (
SELECT `Customer ID`, `Previous Purchases`,
CASE 
    WHEN `Previous Purchases` = 1 THEN 'New'
    WHEN `Previous Purchases` BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment; 

##Q8. What are the top 3 most purchased products within each category? 
with item_counts as (
select `Category`,
`Item Purchased`,
count(`Customer ID`) as total_orders,
ROW_NUMBER()over(partition by `Category` order by count(`Customer ID`) desc) as item_rank
from customer
GROUP BY `Category`, `Item Purchased`
)
SELECT ITEM_RANK, `Category`, `Item Purchased` , TOTAL_ORDERS
FROM ITEM_COUNTS
WHERE ITEM_RANK <=3;

##Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT `Subscription Status`,
count(`Customer ID`) AS REPEAT_BUYERS
FROM customer
where `Previous Purchases`> 5
group by `Subscription Status`;

##Q10. What is the revenue contribution of each age group? 
SELECT 
    CASE 
        WHEN `Age` < 30 THEN 'Under 30'
        WHEN `Age` BETWEEN 30 AND 50 THEN '30-50'
        ELSE 'Over 50'
    END AS AGE_GROUP,
    SUM(`Purchase Amount (USD)`) AS TOTAL_REVENUE
FROM customer
GROUP BY AGE_GROUP
ORDER BY TOTAL_REVENUE DESC;

